export const list = [
    {
      "Title": "Stranger Things",
      "Year": "2016",
      "Rated": "TV-14",
      "Released": "15 Jul 2016",
      "Runtime": "51 min",
      "Genre": "Drama, Fantasy, Horror",
      "Director": "N/A",
      "Writer": "Matt Duffer, Ross Duffer",
      "Actors": "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
      "Plot": "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces to get him back.",
      "Language": "English",
      "Country": "United States",
      "Awards": "Won 12 Primetime Emmys. 83 wins & 216 nominations total",
      "Poster": "https://rukminim2.flixcart.com/image/850/1000/jr3t5e80/poster/a/w/f/medium-stranger-things-poster-for-room-office-13-inch-x-19-inch-original-imafcww8v99r4qhh.jpeg?q=20&crop=false",
      "imdbRating": "8.7",
      "imdbID": "tt4574334",
      "Type": "series"
    },
    {
      "Title": "Inception",
      "Year": "2010",
      "Rated": "PG-13",
      "Released": "16 Jul 2010",
      "Runtime": "148 min",
      "Genre": "Action, Adventure, Sci-Fi",
      "Director": "Christopher Nolan",
      "Writer": "Christopher Nolan",
      "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
      "Plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      "Language": "English, Japanese, French",
      "Country": "United States, United Kingdom",
      "Awards": "Won 4 Oscars. 157 wins & 220 nominations total",
      "Poster": "https://rukminim2.flixcart.com/image/850/1000/j9k8ivk0/poster/2/y/t/medium-inception-poster-print-poster-on-13x19-inches-poster5111-original-imaezyyz4u8m7eyx.jpeg?q=90&crop=false",
      "imdbRating": "8.8",
      "imdbID": "tt1375666",
      "Type": "movie"
    },
    {
      "Title": "Breaking Bad",
      "Year": "2008–2013",
      "Rated": "TV-MA",
      "Released": "20 Jan 2008",
      "Runtime": "49 min",
      "Genre": "Crime, Drama, Thriller",
      "Director": "N/A",
      "Writer": "Vince Gilligan",
      "Actors": "Bryan Cranston, Aaron Paul, Anna Gunn",
      "Plot": "A high school chemistry teacher turned methamphetamine producer partners with a former student to secure his family's future while dealing with the dangers of the drug trade.",
      "Language": "English, Spanish",
      "Country": "United States",
      "Awards": "Won 16 Primetime Emmys. 151 wins & 248 nominations total",
      "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStircbdyLwcauqnR9Kwu8yvS2I_TdiBPI1og&s",
      "imdbRating": "9.5",
      "imdbID": "tt0903747",
      "Type": "series"
    },
    {
      "Title": "The Dark Knight",
      "Year": "2008",
      "Rated": "PG-13",
      "Released": "18 Jul 2008",
      "Runtime": "152 min",
      "Genre": "Action, Crime, Drama",
      "Director": "Christopher Nolan",
      "Writer": "Jonathan Nolan, Christopher Nolan, David S. Goyer",
      "Actors": "Christian Bale, Heath Ledger, Aaron Eckhart",
      "Plot": "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
      "Language": "English, Mandarin",
      "Country": "United States, United Kingdom",
      "Awards": "Won 2 Oscars. 159 wins & 163 nominations total",
      "Poster": "https://rukminim2.flixcart.com/image/850/1000/k8xduvk0/poster/j/m/z/medium-the-dark-knight-poster-decorative-wall-poster-wall-d-cor-original-imafqu8euacqngyh.jpeg?q=90&crop=false",
      "imdbRating": "9.0",
      "imdbID": "tt0468569",
      "Type": "movie"
    },
    {
      "Title": "Interstellar",
      "Year": "2014",
      "Rated": "PG-13",
      "Released": "07 Nov 2014",
      "Runtime": "169 min",
      "Genre": "Adventure, Drama, Sci-Fi",
      "Director": "Christopher Nolan",
      "Writer": "Jonathan Nolan, Christopher Nolan",
      "Actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
      "Plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      "Language": "English",
      "Country": "United States, United Kingdom",
      "Awards": "Won 1 Oscar. 44 wins & 148 nominations total",
      "Poster": "https://m.media-amazon.com/images/I/61wrhEawgQL._AC_UF1000,1000_QL80_.jpg",
      "imdbRating": "8.7",
      "imdbID": "tt0816692",
      "Type": "movie"
    },
    {
      "Title": "Joker",
      "Year": "2019",
      "Rated": "R",
      "Released": "04 Oct 2019",
      "Runtime": "122 min",
      "Genre": "Crime, Drama, Thriller",
      "Director": "Todd Phillips",
      "Writer": "Todd Phillips, Scott Silver, Bob Kane",
      "Actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
      "Plot": "In Gotham City, mentally troubled comedian Arthur Fleck embarks on a downward spiral of social revolution and bloody crime.",
      "Language": "English",
      "Country": "United States, Canada",
      "Awards": "Won 2 Oscars. 118 wins & 233 nominations total",
      "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhixpCa-IEak3FFc5r1_Slm7fh0dekY7y7SA&s",
      "imdbRating": "8.4",
      "imdbID": "tt7286456",
      "Type": "movie"
    }
]
  
  